[package]
name = "tailwind"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = { version = "0.10.9", default-features = false, features = ["std"] }
regex = { version = "1.11.1", default-features = false, features = ["std", "unicode-perl"] }
glob = "0.3.2" 